name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts
publish_to: none

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.

  charts_common:
    path: ../charts_common/
  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: ">=0.15.2"
  logging:
  meta: ">=1.1.1"


dev_dependencies:
  mockito: 
  build_runner: 
  flutter_test:
    sdk: flutter
  test: 
